exclude_paths:
  - '**/!Materials Collection/**'
  - '**/Demigiant/**'
  - '**/DL_Fantasy_RPG_Effects/**' 
  - '**/Dungeon Ground/**'
  - '**/Easy Frames Pack/**'
  - '**/Dungeon Creator Kit LITE/**'
  - '**/InventoryMaster/**'
  - '**/JsonDotNet/**'
  - '**/Level 1 Monster Pack/**'
  - '**/LightShafts/**'
  - '**/LowpolyDungeonAssets/**'
  - '**/Modern UI Pack/**'
  - '**/Particle Ribbon by Moonflower Carnivore/**'
  - '**/Particlecollection_Free samples/**'
  - '**/ProgressBar/**'
  - '**/RenderTexture/**'
  - '**/Resources/**'
  - '**/RpgPack/**'
  - '**/SimpleFantasy/**'
  - '**/StreamingAssets/**'
  - '**/Unity-Logs-Viewer/**'
  - '**/Wood products/**'
  - '**/wooden furnitures/**'
